### ISSUE TITLE
Create repo server repo.tokenscript.org

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/TokenScript-Repo#2]

**Comment by colourful-land** [comment]
Done in the latest commit (oh forgot to do  a PR instead)

You can run it yourself, I hope it works on OS X.

    [weiwu@ip-172-31-19-32 TokenScript-Repo]$ make
    # type: make .htaccess
    [weiwu@ip-172-31-19-32 TokenScript-Repo]$ make .htaccess
    # Finding tsml files
    # shong.wang/2019/05/EntryToken.tsml: Processing with namespace
    # shong.wang/2019/05/EntryToken.tsml: http://tokenscript.org/2019/05/tokenscript
    # shong.wang/2019/05/EntryToken.tsml: contract name: EntryToken
    RewriteRule ^2019/05/0x63cCEF733a093E5Bd773b41C96D3eCE361464942$ shong.wang/2019/05/EntryToken.tsml
    RewriteRule ^2019/05/0xFB82A5a2922A249f32222316b9D1F5cbD3838678$ shong.wang/2019/05/EntryToken.tsml
    RewriteRule ^2019/05/0x7c81DF31BB2f54f03A56Ab25c952bF3Fa39bDF46$ shong.wang/2019/05/EntryToken.tsml
    RewriteRule ^2019/05/0x2B58A9403396463404c2e397DBF37c5EcCAb43e5$ shong.wang/2019/05/EntryToken.tsml
    # No error found. Putting the file in place
    mv htaccess.tmp .htaccess

Then you can see the generated .htaccess:


````
AddType application/xhtml+xml .xhtml
Options +FollowSymLinks
RewriteEngine on
RewriteRule ^2019/05/0x63cCEF733a093E5Bd773b41C96D3eCE361464942$ shong.wang/2019/05/EntryToken.tsml
RewriteRule ^2019/05/0xFB82A5a2922A249f32222316b9D1F5cbD3838678$ shong.wang/2019/05/EntryToken.tsml
RewriteRule ^2019/05/0x7c81DF31BB2f54f03A56Ab25c952bF3Fa39bDF46$ shong.wang/2019/05/EntryToken.tsml
RewriteRule ^2019/05/0x2B58A9403396463404c2e397DBF37c5EcCAb43e5$ shong.wang/2019/05/EntryToken.tsml
````

To test it working, try this:

https://repo.tokenscript.org/2019/05/0x63cCEF733a093E5Bd773b41C96D3eCE361464942
